<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\SessionStories.Providers\SessionStories.Providers.csproj" />
    <ProjectReference Include="..\SessionStories.Tts.Chatterbox\SessionStories.Tts.Chatterbox.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
