/**
 * Cały tekst interfejsu w jednym płaskim obiekcie (właściciel: agent 1).
 * Inne moduły importują `strings` i używają kluczy; brakujące klucze
 * dopisujemy tutaj przy integracji.
 */
export const strings = {
  // --- Aplikacja / nawigacja ---
  appName: 'Opowieści',
  navHome: 'Historie',
  navListen: 'Słuchaj',
  navSettings: 'Ustawienia',

  // --- Ogólne ---
  save: 'Zapisz',
  cancel: 'Anuluj',
  delete: 'Usuń',
  close: 'Zamknij',
  back: 'Wstecz',
  edit: 'Edytuj',
  create: 'Utwórz',
  confirm: 'Potwierdź',
  yes: 'Tak',
  no: 'Nie',
  loading: 'Wczytywanie…',
  saving: 'Zapisywanie…',
  saved: 'Zapisano',
  error: 'Coś poszło nie tak',
  errorNetwork: 'Brak połączenia z serwerem',
  errorNotFound: 'Nie znaleziono',
  retry: 'Spróbuj ponownie',
  optional: '(opcjonalnie)',

  // --- Lista historii ---
  storiesTitle: 'Historie',
  storiesEmpty: 'Nie ma jeszcze żadnych historii. Stwórzcie pierwszą!',
  newStory: 'Nowa historia',
  universeLabel: 'Świat',
  variantsLabel: 'Wersje',
  stageSpec: 'Założenia',
  stageOutline: 'Plan scen',
  stageDraft: 'Tekst',
  stageAudio: 'Audio',
  newStoryTitleHeading: 'Nowa historia',
  newStorySlugLabel: 'Identyfikator folderu',
  newStorySlugPlaceholder: 'np. 2026-08-08-jaskinia',
  newStoryTitleLabel: 'Tytuł',
  newStoryTitlePlaceholder: 'np. Klejnot z Marrowfield',
  newStoryUniverseLabel: 'Świat',
  newStoryVariantLabel: 'Pierwsza wersja (czyja opowieść?)',
  newStoryVariantPlaceholder: 'np. michal',
  newStoryLanguageLabel: 'Język',
  newStoryCreated: 'Historia utworzona',

  // --- Szczegóły historii ---
  storyDetailTitle: 'Historia',
  recollectionsTitle: 'Wspomnienia',
  recollectionsEmpty:
    'Nie ma jeszcze wspomnień. Nagrajcie, co pamiętacie z sesji.',
  recollectionsShared: 'Wspomnienia są wspólne dla wszystkich wersji.',
  addRecollection: 'Dodaj wspomnienie',
  variantLabel: 'Wersja',
  povLabel: 'Bohater',
  languageLabel: 'Język',
  artifactSession: 'Założenia',
  artifactOutline: 'Plan scen',
  artifactDraft: 'Tekst',
  artifactVerify: 'Weryfikacja',
  artifactPendingFacts: 'Nowe fakty',
  artifactAudio: 'Audio',
  goCapture: 'Nagraj wspomnienie',
  goBuilder: 'Ustawienia opowieści',
  goDraft: 'Czytaj i poprawiaj',
  goProgress: 'Postęp',
  goListen: 'Słuchaj',
  startGeneration: 'Generuj historię',
  startVerify: 'Sprawdź zgodność',
  startRenderTts: 'Nagraj lektora',
  addVariant: 'Dodaj wersję',

  // --- Nagrywanie wspomnień (Capture) ---
  captureTitle: 'Opowiedz, co pamiętasz',
  captureHint:
    'Mów swobodnie, po swojemu. Nie musi być po kolei — najważniejsze jest to, co było najciekawsze.',
  capturePersonLabel: 'Kto opowiada?',
  capturePersonPlaceholder: 'np. michal, kuba…',
  captureStart: 'Nagrywaj',
  captureStop: 'Zatrzymaj',
  captureRecording: 'Nagrywanie…',
  capturePickFile: 'Wybierz plik',
  captureUpload: 'Wyślij',
  captureUploading: 'Wysyłanie…',
  captureUploadDone: 'Wysłano! Nagranie zostanie spisane automatycznie.',
  captureTextMode: 'Wolisz napisać?',
  captureTextPlaceholder: 'Zapisz tu swoje wspomnienie…',
  captureExists:
    'Wspomnienie tej osoby już istnieje — wspomnień nie można nadpisywać.',
  captureMicDenied: 'Brak dostępu do mikrofonu. Sprawdź uprawnienia.',
  captureTranscribing: 'Spisywanie nagrania…',
  captureListenBack: 'Odsłuchaj przed wysłaniem',

  // --- Budowa opowieści (SessionBuilder) ---
  builderTitle: 'Ustawienia opowieści',
  builderGivenLabel: 'TAK BYŁO',
  builderInventLabel: 'WYMYŚL',
  builderGivenHint: 'Tak się wydarzyło — przebiegu nie wolno zmieniać.',
  builderInventHint: 'Pole do fantazji — niech historia sama się ułoży.',
  builderBeatsLabel: 'Wydarzenia (po kolei)',
  builderBeatPlaceholder: 'Co się wydarzyło?',
  builderAddBeat: 'Dodaj wydarzenie',
  builderRemoveBeat: 'Usuń wydarzenie',
  builderCastLabel: 'Postacie',
  builderStakesLabel: 'Stawka',
  builderStakesPlaceholder: 'O co toczyła się gra?',
  builderPovLabel: 'Czyimi oczami?',
  builderToneLabel: 'Ton opowieści',
  builderVoiceLabel: 'Głos lektora',
  builderTargetMinutesLabel: 'Docelowa długość (minuty)',
  builderSkipLabel: 'Co pominąć',
  builderSkipPlaceholder: 'np. kłótnie o zasady, przerwy…',
  builderPresetLabel: 'Zacznij od szablonu',
  builderPresetBattleReport: 'Raport z bitwy — wszystko tak było',
  builderPresetRpgSession: 'Sesja RPG — trochę było, trochę wymyśl',
  builderPresetPremise: 'Sam pomysł — wymyśl resztę',
  builderSaveAndGenerate: 'Zapisz i generuj',
  builderRawJson: 'Edytuj JSON',
  builderConflict:
    'Plik założeń zmienił się w międzyczasie. Wczytaj aktualną wersję i nanieś zmiany jeszcze raz.',

  // --- Postęp (Progress / zadania) ---
  progressTitle: 'Postęp',
  jobsTitle: 'Zadania',
  jobsEmpty: 'Brak zadań',
  jobQueued: 'W kolejce',
  jobRunning: 'W toku',
  jobSucceeded: 'Gotowe',
  jobFailed: 'Nie udało się',
  jobCancelled: 'Przerwano',
  jobCancel: 'Przerwij',
  jobCost: 'Koszt',
  jobElapsed: 'Czas',
  jobStage: 'Etap',
  jobLog: 'Dziennik',
  jobTypeTranscribe: 'Spisywanie nagrania',
  jobTypeGenerate: 'Generowanie historii',
  jobTypeRegenScene: 'Nowa wersja sceny',
  jobTypeVerify: 'Sprawdzanie zgodności',
  jobTypeRenderTts: 'Nagrywanie lektora',
  jobEnqueued: 'Dodano do kolejki',
  jobSerialNote: 'Zadania wykonują się po kolei, jedno naraz.',

  // --- Wersja robocza (DraftReview) ---
  draftTitle: 'Wersja robocza',
  draftEmpty: 'Nie ma jeszcze tekstu. Najpierw wygeneruj historię.',
  sceneLabel: 'Scena',
  sceneEdit: 'Edytuj scenę',
  sceneSave: 'Zapisz scenę',
  sceneRegen: 'Wygeneruj na nowo',
  sceneRestore: 'Przywróć poprzednią wersję',
  sceneFeedbackLabel: 'Wskazówka dla nowej wersji',
  sceneFeedbackPlaceholder: 'Co poprawić w tej scenie? (opcjonalnie)',
  sceneRegenQueued: 'Scena trafiła do kolejki',
  verifyFlagsTitle: 'Uwagi weryfikacji',
  verifyClean: 'Bez zastrzeżeń',
  draftConflictTitle: 'Tekst się zmienił',
  draftConflictBody:
    'Ten fragment został w międzyczasie zmieniony (przez generator albo na innym urządzeniu). Możesz wczytać nową wersję albo nadpisać ją swoją.',
  draftConflictReload: 'Wczytaj nową wersję',
  draftConflictOverwrite: 'Nadpisz moją wersją',
  draftSaved: 'Zapisano scenę',

  // --- Słuchanie / odtwarzacz ---
  listenTitle: 'Słuchanie',
  listenEmpty:
    'Nie ma jeszcze żadnych nagrań. Wygeneruj historię i nagraj lektora.',
  playAll: 'Odtwórz wszystko',
  play: 'Odtwórz',
  pause: 'Pauza',
  nextTrack: 'Następna',
  prevTrack: 'Poprzednia',
  nowPlaying: 'Teraz gra',
  queueTitle: 'Kolejka',
  download: 'Pobierz',

  // --- Świat (Universe) ---
  universeTitle: 'Świat',
  tabConstraints: 'Zasady świata',
  tabBible: 'Kronika',
  tabCharacters: 'Postacie',
  tabVoices: 'Głosy',
  tabTones: 'Tony',
  universeFileSaved: 'Zapisano plik',
  universeFileConflict:
    'Plik zmienił się w międzyczasie. Wczytaj aktualną wersję i nanieś zmiany jeszcze raz.',
  pendingFactsTitle: 'Nowe fakty do kroniki',
  pendingFactsEmpty: 'Brak nowych faktów do zatwierdzenia.',
  pendingFactsHint:
    'Fakty z ukończonych historii — zatwierdzone trafią na stałe do kroniki świata.',
  approveSelected: 'Zatwierdź zaznaczone',
  factsApproved: 'Dodano do kroniki',
  factSource: 'Źródło',

  // --- Ustawienia / stan systemu ---
  settingsTitle: 'Ustawienia',
  statusTitle: 'Stan systemu',
  statusClaude: 'Claude CLI',
  statusGpu: 'Karta graficzna',
  statusModels: 'Modele',
  statusWhisper: 'Whisper (spisywanie)',
  statusChatterbox: 'Chatterbox (lektor)',
  statusLibraryRoot: 'Folder biblioteki',
  statusFound: 'Dostępny',
  statusMissing: 'Brak',
  statusVersion: 'Wersja',

  // --- Uzupełnienia z integracji (dawne literały inline z modułów) ---
  // Ogólne
  add: 'Dodaj',
  preview: 'Podgląd',
  refresh: 'Odśwież',
  generate: 'Generuj',
  creating: 'Tworzenie…',
  goBack: 'Wróć',
  backToStory: 'Wróć do opowieści',
  backToList: 'Wróć do listy',
  unsavedChanges: 'Niezapisane zmiany',
  untitled: 'Bez tytułu',
  selectAll: 'Zaznacz wszystko',
  deselectAll: 'Odznacz wszystko',
  emptyFile: 'Pusty plik',
  languagePl: 'polski',
  languageEn: 'angielski',
  discardConfirm: 'Odrzucić niezapisane zmiany?',
  moreActions: 'Więcej działań',
  errorShort: 'błąd',
  titleLabel: 'Tytuł',

  // Klient HTTP
  errorFileChangedOnDisk: 'Plik zmienił się na dysku od czasu odczytu.',
  uploadNetworkError: 'Błąd sieci podczas wysyłania.',
  uploadAborted: 'Wysyłanie przerwane.',

  // Słuchanie
  downloadAll: 'Pobierz wszystkie',
  downloadingAll: 'Pobieranie…',

  // Lista historii
  newStoryDescription: 'Utworzy folder historii i pierwszą wersję.',
  newStoryValidationMissing: 'Podaj tytuł i nazwę wersji.',
  newStorySlugInvalid: 'Slug może zawierać tylko małe litery, cyfry i myślniki.',
  newStoryNoUniverses: 'Brak uniwersów — najpierw dodaj folder uniwersum w bibliotece.',
  universesEmptyOption: 'brak uniwersów',
  storiesLoadError: 'Nie udało się pobrać historii.',
  storiesEmptyHint: 'Zacznij od „Nowa historia”, potem nagrajcie wspomnienia.',

  // Szczegóły historii
  storyNotFound: 'Nie znaleziono historii.',
  variantNameInvalid: 'Nazwa wersji: małe litery, cyfry i myślniki.',
  variantExists: 'Taka wersja już istnieje.',
  cloneTitle: 'Nowa wersja historii',
  cloneDescription: 'Skopiuje ustawienia istniejącej wersji — wspomnienia są wspólne.',
  cloneSourceLabel: 'Kopiuj z wersji',
  cloneNameLabel: 'Nazwa nowej wersji',
  clonePovLabel: 'POV (czyja to opowieść)',
  clonePovPlaceholder: 'np. Kuba — łucznik',
  createVariant: 'Utwórz wersję',
  actionProgress: 'Zobacz postęp',
  actionBuild: 'Zbuduj sesję',
  actionCapture: 'Nagraj wspomnienia',
  actionReadDraft: 'Czytaj szkic',
  sharedAcrossVariants: 'wspólne dla wszystkich wersji',
  textNote: 'notatka tekstowa',
  transcriptChip: 'transkrypcja',
  transcriptPendingChip: 'transkrypcja…',
  povUnset: 'POV nieustawione',
  linkSession: 'sesja',
  linkProgress: 'postęp',
  linkDraft: 'szkic',
  linkAudio: 'audio',

  // Nagrywanie wspomnień (Capture)
  captureHeading: 'Wspomnienia z sesji',
  captureSharedHint: 'Wspólne dla wszystkich wersji. Nagrania audio transkrybują się same.',
  addFile: 'Dodaj plik',
  captureNewPersonLabel: 'Ktoś nowy?',
  captureNewPersonPlaceholder: 'imię, np. zosia',
  uploadedShort: 'wysłano',
  captureCollectedTitle: 'Już zebrane',
  captureEmptyList: 'Jeszcze nic tu nie ma — nagraj pierwsze wspomnienie powyżej.',
  openText: 'otwórz tekst',
  transcriptReloaded: 'Plik zmienił się w międzyczasie — wczytano aktualną wersję.',
  transcriptRawHint: 'Surowa transkrypcja — bałagan jest częścią wspomnienia.',
  transcriptEditWarning:
    'Transkrypcje celowo zostają nieuczesane — tak zapamiętało dziecko i tak ma zostać. Edytuj tylko, gdy Whisper przekręcił słowa.',
  editAnyway: 'Edytuj mimo to',

  // Budowa opowieści (SessionBuilder)
  builderPresetGiven: 'Raport bitewny',
  builderPresetInvent: 'Pomysł',
  builderPresetGivenTitle: 'Zastosować szablon „Raport bitewny”?',
  builderPresetGivenBody: 'Wszystkie beaty zostaną oznaczone jako „TAK BYŁO”.',
  builderPresetInventTitle: 'Zastosować szablon „Pomysł”?',
  builderPresetInventBody: 'Wszystkie beaty zostaną oznaczone jako „WYMYŚL”.',
  builderCastCustomTitle: 'Dodaj własną postać',
  builderCastName: 'Imię',
  builderCastAbout: 'Kim jest (krótko)',
  builderCastRemove: 'Usuń postać',
  builderPovEmpty: 'Zaznacz postacie w obsadzie, aby wybrać POV.',
  builderOutcomeLabel: 'Finał',
  builderSkipRemove: 'Usuń z listy pominięć',
  builderVoiceDefault: '(domyślny z uniwersum)',
  builderMoveUp: 'Przenieś wyżej',
  builderMoveDown: 'Przenieś niżej',
  builderGenerateHint: 'Zapisz zmiany przed generowaniem',
  builderConflictTitle: 'Plik zmieniony na dysku — przeładować?',
  builderConflictBody:
    'Plik session.json zmienił się od ostatniego wczytania (może edycja ręczna). Przeładowanie odrzuci lokalne zmiany. Dalsza edycja sprawi, że następny zapis nadpisze wersję z dysku.',
  builderConflictReload: 'Przeładuj z serwera',
  builderConflictKeep: 'Edytuj dalej',
  builderLoadError: 'Nie udało się wczytać sesji',
  builderSessionBroken: 'Plik sesji nie jest poprawnym obiektem JSON.',

  // Postęp (Progress)
  progressLoadingJobs: 'Wczytywanie zadań…',
  progressNoJobs: 'Brak zadań dla tego wariantu.',
  jobsLoadError: 'Nie udało się pobrać listy zadań.',
  jobQueuedNote: 'Zadanie czeka w kolejce — zadania wykonują się pojedynczo.',
  jobCancelConfirm: 'Na pewno przerwać to zadanie?',
  jobFailedNote: 'Zadanie zakończyło się błędem.',
  stageExtract: 'Ekstrakcja faktów',
  stageOutlineStep: 'Szkielet scen',
  stageScenes: 'Sceny',
  stageVerify: 'Weryfikacja',
  stageBible: 'Fakty do biblii',

  // Wersja robocza (DraftReview)
  draftReviewTitle: 'Przegląd szkicu',
  draftLoading: 'Wczytywanie szkicu…',
  draftEmptyForVariant: 'Nie ma jeszcze szkicu dla tego wariantu.',
  sceneRestoreConfirm: 'Przywrócić poprzednią wersję tej sceny?',
  sceneRegenInProgress: 'Nowa wersja sceny w przygotowaniu…',
  sceneRegenTitle: 'Wygeneruj scenę ponownie',
  sceneRegenHint: 'Możesz dodać wskazówkę — co poprawić w nowej wersji.',
  sceneRegenPlaceholder: 'Np. mniej opisów, więcej dialogu…',
  enqueueError: 'Nie udało się dodać zadania.',
  renderTtsEnqueueError: 'Nie udało się dodać zadania renderowania.',
  verifyAgain: 'Weryfikuj ponownie',
  verifyRunning: 'Weryfikacja…',
  sceneRegenOwnNotesLabel: 'Własne uwagi (opcjonalnie)',
  sceneRegenNothingSelectedHint: 'Zaznacz uwagi albo napisz własne',

  // Uwagi weryfikacji — etykiety kategorii (slug reguły → język ludzki)
  verifyRuleGivenDrift: 'Zmienione fakty — tak nie było',
  verifyRuleRegister: 'Styl narracji',
  verifyRuleAnachronism: 'Anachronizm',
  verifyRuleNaming: 'Nazewnictwo',
  verifyRuleHardRules: 'Zasady świata',
  verifyRuleCanon: 'Sprzeczne z kroniką',
  verifyRuleTone: 'Ton opowieści',
  draftConflictDiskTitle: 'Szkic zmienił się na dysku',
  draftConflictDiskBody:
    'plik szkicu został w międzyczasie zmieniony (np. przez regenerację albo ręczną edycję). Co zrobić z Twoją wersją?',

  // Świat (Universe)
  universeConflictTitle: 'Plik zmienił się na dysku',
  fontToggleAria: 'Krój pisma',
  fontSerif: 'Szeryf',
  fontMono: 'Mono',
  tabFacts: 'Fakty',
  voicesShowCards: 'Pokaż karty',
  voicesInvalidJson: 'Nieprawidłowy JSON — plik i tak można zapisać',
  voicesParseError: 'Nie udało się odczytać voices.json — użyj edytora JSON',
  voicesEmpty: 'Brak zdefiniowanych głosów',

  // Ustawienia
  settingsClaudeMissingTitle: 'Brak Claude CLI',
  settingsClaudeMissingBody1: 'Nie znaleziono polecenia',
  settingsClaudeMissingBody2:
    '. Generowanie historii nie będzie działać. Zainstaluj Claude Code i zaloguj się — uruchom',
  settingsClaudeMissingBody3: 'w terminalu i przejdź logowanie subskrypcją.',
  settingsModelsHintPrefix: 'Brakujące modele pobierze',
  settingsBypassBody:
    'Ta aplikacja to tylko widok na zwykłe pliki — bez bazy danych i bez blokad. Każdy plik możesz edytować ręcznie (albo podejrzeć, co zrobił generator), a panel zobaczy zmiany od razu. Jeśli panel kiedyś przeszkadza, edytuj pliki bezpośrednio:',
  settingsGeneratorHeading: 'Generator',
  settingsLibraryHeading: 'Biblioteka',
  settingsBypassTitle: 'Panel można pominąć',
} as const

export type StringKey = keyof typeof strings
